// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using padelya_api.Data;

#nullable disable

namespace padelya_api.Migrations
{
    [DbContext(typeof(PadelYaDbContext))]
    [Migration("20250827152015_AddPermissionDisplayFields")]
    partial class AddPermissionDisplayFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Couple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Couples");
                });

            modelBuilder.Entity("CouplePlayer", b =>
                {
                    b.Property<int>("CoupleId")
                        .HasColumnType("int");

                    b.Property<int>("PlayersId")
                        .HasColumnType("int");

                    b.HasKey("CoupleId", "PlayersId");

                    b.HasIndex("PlayersId");

                    b.ToTable("CouplePlayer");
                });

            modelBuilder.Entity("CourtSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourtId = 1,
                            Date = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeOnly(10, 30, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CourtId = 1,
                            Date = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeOnly(15, 0, 0),
                            StartTime = new TimeOnly(13, 30, 0),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CourtId = 2,
                            Date = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeOnly(12, 0, 0),
                            StartTime = new TimeOnly(10, 30, 0),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CourtId = 3,
                            Date = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeOnly(19, 30, 0),
                            StartTime = new TimeOnly(18, 0, 0),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("LessonEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("PersonId");

                    b.ToTable("LessonEnrollments");
                });

            modelBuilder.Entity("RolCompositePermission", b =>
                {
                    b.Property<int>("PermissionComponentId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionComponentId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolCompositePermission");

                    b.HasData(
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 2,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 3,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 4,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 5,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 6,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 7,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 8,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 9,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 10,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 11,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 12,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 13,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 14,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 15,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 16,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 17,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 18,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 19,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 20,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 21,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 22,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 23,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 24,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 25,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 26,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 27,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 28,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 29,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 30,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 31,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 32,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 33,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 34,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 35,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 36,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 37,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 38,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 39,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 40,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 41,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 42,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 43,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 44,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 45,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 46,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 47,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 48,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 49,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 4,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 6,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 22,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 23,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 24,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 25,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 27,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 28,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 41,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 42,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 43,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 44,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 45,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 46,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 47,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 48,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 49,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 31,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 33,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 10,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 11,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 12,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 13,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 14,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 15,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 16,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 17,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 18,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 4,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 6,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 25,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 26,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 28,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 31,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 33,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 37,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 42,
                            RoleId = 102
                        });
                });

            modelBuilder.Entity("RoutineExercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("RoutineId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseId", "RoutineId");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineExercise");
                });

            modelBuilder.Entity("RoutinePlayer", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RoutineId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "RoutineId");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutinePlayer");
                });

            modelBuilder.Entity("padelya_api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourtSlotId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourtSlotId")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourtSlotId = 1,
                            PersonId = 1,
                            Status = "ReservedPaid"
                        },
                        new
                        {
                            Id = 2,
                            CourtSlotId = 2,
                            PersonId = 2,
                            Status = "ReservedDeposit"
                        },
                        new
                        {
                            Id = 3,
                            CourtSlotId = 3,
                            PersonId = 1,
                            Status = "ReservedPaid"
                        },
                        new
                        {
                            Id = 4,
                            CourtSlotId = 4,
                            PersonId = 3,
                            Status = "ReservedPaid"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Class.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("padelya_api.Models.Class.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("padelya_api.Models.Class.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Backhand")
                        .HasColumnType("real");

                    b.Property<float>("Bandeja")
                        .HasColumnType("real");

                    b.Property<float>("Drive")
                        .HasColumnType("real");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<float>("Serve")
                        .HasColumnType("real");

                    b.Property<float>("Smash")
                        .HasColumnType("real");

                    b.Property<float>("Vibora")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("padelya_api.Models.Complex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClosingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Complex");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Sports Avenue, Downtown District, City Center",
                            ClosingTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PadelYa Sports Complex",
                            OpeningTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingPrice")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<int>("ComplexId")
                        .HasColumnType("int");

                    b.Property<int>("CourtStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingPrice = 15000,
                            ClosingTime = new TimeOnly(23, 0, 0),
                            ComplexId = 1,
                            CourtStatus = 1,
                            Name = "Court 1 - Premium",
                            OpeningTime = new TimeOnly(6, 0, 0),
                            Type = "Cristal"
                        },
                        new
                        {
                            Id = 2,
                            BookingPrice = 20000,
                            ClosingTime = new TimeOnly(23, 0, 0),
                            ComplexId = 1,
                            CourtStatus = 1,
                            Name = "Court 2 - Standard",
                            OpeningTime = new TimeOnly(6, 0, 0),
                            Type = "Césped"
                        },
                        new
                        {
                            Id = 3,
                            BookingPrice = 12000,
                            ClosingTime = new TimeOnly(23, 0, 0),
                            ComplexId = 1,
                            CourtStatus = 1,
                            Name = "Court 3 - Standard",
                            OpeningTime = new TimeOnly(6, 0, 0),
                            Type = "Cristal"
                        },
                        new
                        {
                            Id = 4,
                            BookingPrice = 25000,
                            ClosingTime = new TimeOnly(23, 0, 0),
                            ComplexId = 1,
                            CourtStatus = 0,
                            Name = "Court 4 - Premium",
                            OpeningTime = new TimeOnly(6, 0, 0),
                            Type = "Césped"
                        },
                        new
                        {
                            Id = 5,
                            BookingPrice = 20000,
                            ClosingTime = new TimeOnly(23, 0, 0),
                            ComplexId = 1,
                            CourtStatus = 1,
                            Name = "Court 5 - Indoor",
                            OpeningTime = new TimeOnly(6, 0, 0),
                            Type = "Cristal"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Reservas",
                            Name = "booking"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Canchas",
                            Name = "court"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Usuarios",
                            Name = "user"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Roles",
                            Name = "role"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Torneos",
                            Name = "tournament"
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Clases",
                            Name = "lesson"
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Rutinas",
                            Name = "routine"
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "Comentarios",
                            Name = "feedback"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LessonEnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("TournamentEnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("LessonEnrollmentId")
                        .IsUnique()
                        .HasFilter("[LessonEnrollmentId] IS NOT NULL");

                    b.HasIndex("TournamentEnrollmentId")
                        .IsUnique()
                        .HasFilter("[TournamentEnrollmentId] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("padelya_api.Models.PermissionComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("PermissionComponents");

                    b.HasDiscriminator<string>("PermissionType").HasValue("PermissionComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("padelya_api.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("PersonType").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollmentEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnrollmentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EnrollmentStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TournamentEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TournamentStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TournamentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("TournamentBrackets");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoupleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentEnrollments");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BracketId")
                        .HasColumnType("int");

                    b.Property<int>("CoupleOneId")
                        .HasColumnType("int");

                    b.Property<int>("CoupleTwoId")
                        .HasColumnType("int");

                    b.Property<int>("CourtSlotId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TournamentMatchState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BracketId");

                    b.HasIndex("CoupleOneId");

                    b.HasIndex("CoupleTwoId");

                    b.HasIndex("CourtSlotId")
                        .IsUnique();

                    b.ToTable("TournamentMatches");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPhases");
                });

            modelBuilder.Entity("padelya_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@test.com",
                            Name = "Juan",
                            PasswordHash = "test",
                            PersonId = 1,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 102,
                            StatusId = 1,
                            Surname = "Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@test.com",
                            Name = "Ana",
                            PasswordHash = "test",
                            PersonId = 2,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 102,
                            StatusId = 1,
                            Surname = "García"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@test.com",
                            Name = "Luis",
                            PasswordHash = "test",
                            PersonId = 3,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 102,
                            StatusId = 1,
                            Surname = "Martínez"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("padelya_api.models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CourtSlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourtSlotId")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("padelya_api.Models.RolComposite", b =>
                {
                    b.HasBaseType("padelya_api.Models.PermissionComponent");

                    b.HasDiscriminator().HasValue("Composite");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Administrador",
                            PermissionType = "Composite"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Profesor",
                            PermissionType = "Composite"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Jugador",
                            PermissionType = "Composite"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.SimplePermission", b =>
                {
                    b.HasBaseType("padelya_api.Models.PermissionComponent");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasIndex("ModuleId");

                    b.HasDiscriminator().HasValue("Simple");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "booking:make",
                            PermissionType = "Simple",
                            Description = "Permite al jugador crear su propia reserva",
                            DisplayName = "Crear reserva (cliente)",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "booking:create",
                            PermissionType = "Simple",
                            Description = "Permite crear reservas para cualquier usuario",
                            DisplayName = "Crear reserva",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "booking:edit",
                            PermissionType = "Simple",
                            Description = "Permite modificar reservas existentes",
                            DisplayName = "Editar reserva",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "booking:cancel",
                            PermissionType = "Simple",
                            Description = "Permite cancelar reservas",
                            DisplayName = "Cancelar reserva",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "booking:view",
                            PermissionType = "Simple",
                            Description = "Permite ver todas las reservas",
                            DisplayName = "Ver reservas",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "booking:view_own",
                            PermissionType = "Simple",
                            Description = "Permite ver las reservas del usuario",
                            DisplayName = "Ver reservas propias",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "booking:assign_user",
                            PermissionType = "Simple",
                            Description = "Permite asignar un usuario a una reserva",
                            DisplayName = "Asignar usuario a reserva",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "booking:mark_paid",
                            PermissionType = "Simple",
                            Description = "Permite marcar la reserva como pagada",
                            DisplayName = "Marcar reserva como pagada",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "tournament:create",
                            PermissionType = "Simple",
                            Description = "Permite crear nuevos torneos",
                            DisplayName = "Crear torneo",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "tournament:edit",
                            PermissionType = "Simple",
                            Description = "Permite editar datos de torneos",
                            DisplayName = "Editar torneo",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "tournament:cancel",
                            PermissionType = "Simple",
                            Description = "Permite cancelar torneos",
                            DisplayName = "Cancelar torneo",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 12,
                            Name = "tournament:view",
                            PermissionType = "Simple",
                            Description = "Permite ver torneos",
                            DisplayName = "Ver torneos",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "tournament:join",
                            PermissionType = "Simple",
                            Description = "Permite inscribir participantes a un torneo",
                            DisplayName = "Inscribir en torneo",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "tournament:assign_user",
                            PermissionType = "Simple",
                            Description = "Permite asignar usuarios a un torneo",
                            DisplayName = "Asignar usuario a torneo",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "tournament:manage_scores",
                            PermissionType = "Simple",
                            Description = "Permite cargar y gestionar resultados de partidos",
                            DisplayName = "Gestionar resultados",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 16,
                            Name = "tournament:generate_bracket",
                            PermissionType = "Simple",
                            Description = "Permite generar el cuadro del torneo",
                            DisplayName = "Generar cuadro",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 17,
                            Name = "tournament:schedule_matches",
                            PermissionType = "Simple",
                            Description = "Permite programar los partidos del torneo",
                            DisplayName = "Programar partidos",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 18,
                            Name = "court:create",
                            PermissionType = "Simple",
                            Description = "Permite crear nuevas canchas",
                            DisplayName = "Crear cancha",
                            ModuleId = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "court:edit",
                            PermissionType = "Simple",
                            Description = "Permite editar información de canchas",
                            DisplayName = "Editar cancha",
                            ModuleId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "court:delete",
                            PermissionType = "Simple",
                            Description = "Permite eliminar canchas",
                            DisplayName = "Eliminar cancha",
                            ModuleId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "court:view",
                            PermissionType = "Simple",
                            Description = "Permite ver todas las canchas",
                            DisplayName = "Ver canchas",
                            ModuleId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "lesson:create",
                            PermissionType = "Simple",
                            Description = "Permite crear nuevas clases",
                            DisplayName = "Crear clase",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 23,
                            Name = "lesson:edit",
                            PermissionType = "Simple",
                            Description = "Permite editar clases",
                            DisplayName = "Editar clase",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 24,
                            Name = "lesson:cancel",
                            PermissionType = "Simple",
                            Description = "Permite cancelar clases",
                            DisplayName = "Cancelar clase",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 25,
                            Name = "lesson:view",
                            PermissionType = "Simple",
                            Description = "Permite ver clases",
                            DisplayName = "Ver clases",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 26,
                            Name = "lesson:join",
                            PermissionType = "Simple",
                            Description = "Permite inscribirse a clases",
                            DisplayName = "Inscribirse en clase",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 27,
                            Name = "lesson:assign_user",
                            PermissionType = "Simple",
                            Description = "Permite asignar usuarios a una clase",
                            DisplayName = "Asignar usuario a clase",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 28,
                            Name = "lesson:leave",
                            PermissionType = "Simple",
                            Description = "Permite darse de baja de una clase",
                            DisplayName = "Salir de clase",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 29,
                            Name = "user:create",
                            PermissionType = "Simple",
                            Description = "Permite crear nuevos usuarios",
                            DisplayName = "Crear usuario",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 30,
                            Name = "user:edit",
                            PermissionType = "Simple",
                            Description = "Permite editar usuarios",
                            DisplayName = "Editar usuario",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 31,
                            Name = "user:edit_self",
                            PermissionType = "Simple",
                            Description = "Permite que el usuario edite su propio perfil",
                            DisplayName = "Editar perfil propio",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 32,
                            Name = "user:view",
                            PermissionType = "Simple",
                            Description = "Permite ver todos los usuarios",
                            DisplayName = "Ver usuarios",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 33,
                            Name = "user:view_own",
                            PermissionType = "Simple",
                            Description = "Permite ver la información del propio usuario",
                            DisplayName = "Ver perfil propio",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 34,
                            Name = "user:assign_roles",
                            PermissionType = "Simple",
                            Description = "Permite asignar roles a usuarios",
                            DisplayName = "Asignar roles",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 35,
                            Name = "user:deactivate",
                            PermissionType = "Simple",
                            Description = "Permite desactivar usuarios",
                            DisplayName = "Desactivar usuario",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 36,
                            Name = "role:create",
                            PermissionType = "Simple",
                            Description = "Permite crear roles",
                            DisplayName = "Crear rol",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 37,
                            Name = "role:edit",
                            PermissionType = "Simple",
                            Description = "Permite editar roles",
                            DisplayName = "Editar rol",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 38,
                            Name = "role:delete",
                            PermissionType = "Simple",
                            Description = "Permite eliminar roles",
                            DisplayName = "Eliminar rol",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 39,
                            Name = "role:permission:assign",
                            PermissionType = "Simple",
                            Description = "Permite agregar o quitar permisos de un rol",
                            DisplayName = "Asignar permisos a rol",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 40,
                            Name = "role:view",
                            PermissionType = "Simple",
                            Description = "Permite ver todos los roles",
                            DisplayName = "Ver roles",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 41,
                            Name = "routine:create",
                            PermissionType = "Simple",
                            Description = "Permite crear rutinas",
                            DisplayName = "Crear rutina",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 42,
                            Name = "routine:edit",
                            PermissionType = "Simple",
                            Description = "Permite editar rutinas",
                            DisplayName = "Editar rutina",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 43,
                            Name = "routine:delete",
                            PermissionType = "Simple",
                            Description = "Permite eliminar rutinas",
                            DisplayName = "Eliminar rutina",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 44,
                            Name = "routine:view",
                            PermissionType = "Simple",
                            Description = "Permite ver rutinas",
                            DisplayName = "Ver rutinas",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 45,
                            Name = "routine:assign_user",
                            PermissionType = "Simple",
                            Description = "Permite asignar usuarios a una rutina",
                            DisplayName = "Asignar usuario a rutina",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 46,
                            Name = "feedback:create",
                            PermissionType = "Simple",
                            Description = "Permite crear comentarios",
                            DisplayName = "Crear comentario",
                            ModuleId = 8
                        },
                        new
                        {
                            Id = 47,
                            Name = "feedback:edit",
                            PermissionType = "Simple",
                            Description = "Permite editar comentarios",
                            DisplayName = "Editar comentario",
                            ModuleId = 8
                        },
                        new
                        {
                            Id = 48,
                            Name = "feedback:delete",
                            PermissionType = "Simple",
                            Description = "Permite eliminar comentarios",
                            DisplayName = "Eliminar comentario",
                            ModuleId = 8
                        },
                        new
                        {
                            Id = 49,
                            Name = "feedback:view",
                            PermissionType = "Simple",
                            Description = "Permite ver comentarios",
                            DisplayName = "Ver comentarios",
                            ModuleId = 8
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Player", b =>
                {
                    b.HasBaseType("padelya_api.Models.Person");

                    b.Property<string>("PreferredPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Primera",
                            PreferredPosition = "Derecha"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Segunda",
                            PreferredPosition = "Revés"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1994, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Tercera",
                            PreferredPosition = "Derecha"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Teacher", b =>
                {
                    b.HasBaseType("padelya_api.Models.Person");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("CouplePlayer", b =>
                {
                    b.HasOne("Couple", null)
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourtSlot", b =>
                {
                    b.HasOne("padelya_api.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("LessonEnrollment", b =>
                {
                    b.HasOne("padelya_api.models.Lesson", "Lesson")
                        .WithMany("Enrollments")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RolCompositePermission", b =>
                {
                    b.HasOne("padelya_api.Models.PermissionComponent", null)
                        .WithMany()
                        .HasForeignKey("PermissionComponentId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.RolComposite", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoutineExercise", b =>
                {
                    b.HasOne("padelya_api.Models.Class.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.Class.Routine", null)
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoutinePlayer", b =>
                {
                    b.HasOne("padelya_api.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.Class.Routine", null)
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("padelya_api.Models.Booking", b =>
                {
                    b.HasOne("CourtSlot", "CourtSlot")
                        .WithOne("Booking")
                        .HasForeignKey("padelya_api.Models.Booking", "CourtSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourtSlot");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("padelya_api.Models.Class.Routine", b =>
                {
                    b.HasOne("padelya_api.Models.Teacher", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("padelya_api.Models.Class.Stats", b =>
                {
                    b.HasOne("padelya_api.models.Lesson", null)
                        .WithMany("Reports")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("padelya_api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("padelya_api.Models.Court", b =>
                {
                    b.HasOne("padelya_api.Models.Complex", null)
                        .WithMany("Courts")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("padelya_api.Models.Payment", b =>
                {
                    b.HasOne("padelya_api.Models.Booking", null)
                        .WithMany("Payments")
                        .HasForeignKey("BookingId");

                    b.HasOne("LessonEnrollment", null)
                        .WithOne("Payment")
                        .HasForeignKey("padelya_api.Models.Payment", "LessonEnrollmentId");

                    b.HasOne("padelya_api.Models.Tournament.TournamentEnrollment", null)
                        .WithOne("Payment")
                        .HasForeignKey("padelya_api.Models.Payment", "TournamentEnrollmentId");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentBracket", b =>
                {
                    b.HasOne("padelya_api.Models.Tournament.TournamentPhase", null)
                        .WithMany("Brackets")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentEnrollment", b =>
                {
                    b.HasOne("Couple", "Couple")
                        .WithMany()
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.Tournament.Tournament", "Tournament")
                        .WithMany("Enrollments")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Couple");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentMatch", b =>
                {
                    b.HasOne("padelya_api.Models.Tournament.TournamentBracket", null)
                        .WithMany("Matches")
                        .HasForeignKey("BracketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Couple", "CoupleOne")
                        .WithMany()
                        .HasForeignKey("CoupleOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Couple", "CoupleTwo")
                        .WithMany()
                        .HasForeignKey("CoupleTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtSlot", "CourtSlot")
                        .WithOne("TournamentMatch")
                        .HasForeignKey("padelya_api.Models.Tournament.TournamentMatch", "CourtSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoupleOne");

                    b.Navigation("CoupleTwo");

                    b.Navigation("CourtSlot");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentPhase", b =>
                {
                    b.HasOne("padelya_api.Models.Tournament.Tournament", null)
                        .WithMany("TournamentPhases")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("padelya_api.Models.User", b =>
                {
                    b.HasOne("padelya_api.Models.Person", "Person")
                        .WithOne()
                        .HasForeignKey("padelya_api.Models.User", "PersonId");

                    b.HasOne("padelya_api.Models.RolComposite", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.UserStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("padelya_api.models.Lesson", b =>
                {
                    b.HasOne("CourtSlot", "CourtSlot")
                        .WithOne("Lesson")
                        .HasForeignKey("padelya_api.models.Lesson", "CourtSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourtSlot");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("padelya_api.Models.SimplePermission", b =>
                {
                    b.HasOne("padelya_api.Models.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CourtSlot", b =>
                {
                    b.Navigation("Booking")
                        .IsRequired();

                    b.Navigation("Lesson")
                        .IsRequired();

                    b.Navigation("TournamentMatch")
                        .IsRequired();
                });

            modelBuilder.Entity("LessonEnrollment", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("padelya_api.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("padelya_api.Models.Complex", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("padelya_api.Models.Module", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.Tournament", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("TournamentPhases");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentBracket", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentEnrollment", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("padelya_api.Models.Tournament.TournamentPhase", b =>
                {
                    b.Navigation("Brackets");
                });

            modelBuilder.Entity("padelya_api.models.Lesson", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
