// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using padelya_api.Data;

#nullable disable

namespace padelya_api.Migrations
{
    [DbContext(typeof(PadelYaDbContext))]
    [Migration("20250703031702_AddComplexSeeding")]
    partial class AddComplexSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolCompositePermission", b =>
                {
                    b.Property<int>("PermissionComponentId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionComponentId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolCompositePermission");

                    b.HasData(
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 2,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 3,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 4,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 5,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 6,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 7,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 8,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 9,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 10,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 11,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 12,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 13,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 14,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 15,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 16,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 17,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 18,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 19,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 20,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 21,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 22,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 23,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 24,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 25,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 26,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 27,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 28,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 29,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 30,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 31,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 32,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 33,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 34,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 35,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 36,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 37,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 38,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 39,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 40,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 41,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 42,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 5,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 6,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 16,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 17,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 19,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 21,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 34,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 35,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 37,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 38,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 39,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 40,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 42,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 25,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 26,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 5,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 6,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 20,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 22,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 19,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 37,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 42,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 25,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 26,
                            RoleId = 102
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Complex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClosingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Complex");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Sports Avenue, Downtown District, City Center",
                            ClosingTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PadelYa Sports Complex",
                            OpeningTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingPrice")
                        .HasColumnType("int");

                    b.Property<int>("ComplexId")
                        .HasColumnType("int");

                    b.Property<int>("CourtStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingPrice = 15000,
                            ComplexId = 1,
                            CourtStatus = 0,
                            Name = "Court 1 - Premium"
                        },
                        new
                        {
                            Id = 2,
                            BookingPrice = 20000,
                            ComplexId = 1,
                            CourtStatus = 0,
                            Name = "Court 2 - Standard"
                        },
                        new
                        {
                            Id = 3,
                            BookingPrice = 12000,
                            ComplexId = 1,
                            CourtStatus = 0,
                            Name = "Court 3 - Standard"
                        },
                        new
                        {
                            Id = 4,
                            BookingPrice = 25000,
                            ComplexId = 1,
                            CourtStatus = 1,
                            Name = "Court 4 - Premium"
                        },
                        new
                        {
                            Id = 5,
                            BookingPrice = 20000,
                            ComplexId = 1,
                            CourtStatus = 0,
                            Name = "Court 5 - Indoor"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.CourtAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Weekday")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourtId = 1,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 1
                        },
                        new
                        {
                            Id = 2,
                            CourtId = 1,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 2
                        },
                        new
                        {
                            Id = 3,
                            CourtId = 1,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 3
                        },
                        new
                        {
                            Id = 4,
                            CourtId = 1,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 4
                        },
                        new
                        {
                            Id = 5,
                            CourtId = 1,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 5
                        },
                        new
                        {
                            Id = 6,
                            CourtId = 1,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 6
                        },
                        new
                        {
                            Id = 7,
                            CourtId = 1,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 0
                        },
                        new
                        {
                            Id = 8,
                            CourtId = 2,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 1
                        },
                        new
                        {
                            Id = 9,
                            CourtId = 2,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 2
                        },
                        new
                        {
                            Id = 10,
                            CourtId = 2,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 3
                        },
                        new
                        {
                            Id = 11,
                            CourtId = 2,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 4
                        },
                        new
                        {
                            Id = 12,
                            CourtId = 2,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 5
                        },
                        new
                        {
                            Id = 13,
                            CourtId = 2,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 6
                        },
                        new
                        {
                            Id = 14,
                            CourtId = 2,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 0
                        },
                        new
                        {
                            Id = 15,
                            CourtId = 3,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 1
                        },
                        new
                        {
                            Id = 16,
                            CourtId = 3,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 2
                        },
                        new
                        {
                            Id = 17,
                            CourtId = 3,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 3
                        },
                        new
                        {
                            Id = 18,
                            CourtId = 3,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 4
                        },
                        new
                        {
                            Id = 19,
                            CourtId = 3,
                            EndTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 5
                        },
                        new
                        {
                            Id = 20,
                            CourtId = 3,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 6
                        },
                        new
                        {
                            Id = 21,
                            CourtId = 3,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 0
                        },
                        new
                        {
                            Id = 22,
                            CourtId = 5,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 1
                        },
                        new
                        {
                            Id = 23,
                            CourtId = 5,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 2
                        },
                        new
                        {
                            Id = 24,
                            CourtId = 5,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 3
                        },
                        new
                        {
                            Id = 25,
                            CourtId = 5,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 4
                        },
                        new
                        {
                            Id = 26,
                            CourtId = 5,
                            EndTime = new DateTime(2024, 1, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 5
                        },
                        new
                        {
                            Id = 27,
                            CourtId = 5,
                            EndTime = new DateTime(2024, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 6
                        },
                        new
                        {
                            Id = 28,
                            CourtId = 5,
                            EndTime = new DateTime(2024, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Weekday = 0
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "booking"
                        },
                        new
                        {
                            Id = 2,
                            Name = "court"
                        },
                        new
                        {
                            Id = 3,
                            Name = "user"
                        },
                        new
                        {
                            Id = 4,
                            Name = "role"
                        },
                        new
                        {
                            Id = 5,
                            Name = "tournament"
                        },
                        new
                        {
                            Id = 6,
                            Name = "class"
                        },
                        new
                        {
                            Id = 7,
                            Name = "routine"
                        },
                        new
                        {
                            Id = 8,
                            Name = "feedback"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.PermissionComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("PermissionComponents");

                    b.HasDiscriminator<string>("PermissionType").HasValue("PermissionComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("padelya_api.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("PersonType").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("padelya_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("padelya_api.Models.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.RolComposite", b =>
                {
                    b.HasBaseType("padelya_api.Models.PermissionComponent");

                    b.HasDiscriminator().HasValue("Composite");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Admin",
                            PermissionType = "Composite"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Teacher",
                            PermissionType = "Composite"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Player",
                            PermissionType = "Composite"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.SimplePermission", b =>
                {
                    b.HasBaseType("padelya_api.Models.PermissionComponent");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasIndex("ModuleId");

                    b.HasDiscriminator().HasValue("Simple");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "booking:make",
                            PermissionType = "Simple",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "booking:create",
                            PermissionType = "Simple",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "booking:edit",
                            PermissionType = "Simple",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "booking:cancel",
                            PermissionType = "Simple",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "booking:view",
                            PermissionType = "Simple",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "booking:view_own",
                            PermissionType = "Simple",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "booking:assign_user",
                            PermissionType = "Simple",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "booking:mark_paid",
                            PermissionType = "Simple",
                            ModuleId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "tournament:create",
                            PermissionType = "Simple",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "tournament:edit",
                            PermissionType = "Simple",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "tournament:cancel",
                            PermissionType = "Simple",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 12,
                            Name = "tournament:view",
                            PermissionType = "Simple",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "tournament:join",
                            PermissionType = "Simple",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "tournament:assign_user",
                            PermissionType = "Simple",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "tournament:manage_scores",
                            PermissionType = "Simple",
                            ModuleId = 5
                        },
                        new
                        {
                            Id = 16,
                            Name = "class:create",
                            PermissionType = "Simple",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 17,
                            Name = "class:edit",
                            PermissionType = "Simple",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 18,
                            Name = "class:cancel",
                            PermissionType = "Simple",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 19,
                            Name = "class:view",
                            PermissionType = "Simple",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 20,
                            Name = "class:join",
                            PermissionType = "Simple",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 21,
                            Name = "class:assign_user",
                            PermissionType = "Simple",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 22,
                            Name = "class:leave",
                            PermissionType = "Simple",
                            ModuleId = 6
                        },
                        new
                        {
                            Id = 23,
                            Name = "user:create",
                            PermissionType = "Simple",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "user:edit",
                            PermissionType = "Simple",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "user:edit_self",
                            PermissionType = "Simple",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 26,
                            Name = "user:view",
                            PermissionType = "Simple",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "user:assign_roles",
                            PermissionType = "Simple",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "user:deactivate",
                            PermissionType = "Simple",
                            ModuleId = 3
                        },
                        new
                        {
                            Id = 29,
                            Name = "role:create",
                            PermissionType = "Simple",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 30,
                            Name = "role:edit",
                            PermissionType = "Simple",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 31,
                            Name = "role:delete",
                            PermissionType = "Simple",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 32,
                            Name = "role:permission:assign",
                            PermissionType = "Simple",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 33,
                            Name = "role:view",
                            PermissionType = "Simple",
                            ModuleId = 4
                        },
                        new
                        {
                            Id = 34,
                            Name = "routine:create",
                            PermissionType = "Simple",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 35,
                            Name = "routine:edit",
                            PermissionType = "Simple",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 36,
                            Name = "routine:delete",
                            PermissionType = "Simple",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 37,
                            Name = "routine:view",
                            PermissionType = "Simple",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 38,
                            Name = "routine:assign_user",
                            PermissionType = "Simple",
                            ModuleId = 7
                        },
                        new
                        {
                            Id = 39,
                            Name = "feedback:create",
                            PermissionType = "Simple",
                            ModuleId = 8
                        },
                        new
                        {
                            Id = 40,
                            Name = "feedback:edit",
                            PermissionType = "Simple",
                            ModuleId = 8
                        },
                        new
                        {
                            Id = 41,
                            Name = "feedback:delete",
                            PermissionType = "Simple",
                            ModuleId = 8
                        },
                        new
                        {
                            Id = 42,
                            Name = "feedback:view",
                            PermissionType = "Simple",
                            ModuleId = 8
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Player", b =>
                {
                    b.HasBaseType("padelya_api.Models.Person");

                    b.Property<string>("PreferredPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("padelya_api.Models.Teacher", b =>
                {
                    b.HasBaseType("padelya_api.Models.Person");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("RolCompositePermission", b =>
                {
                    b.HasOne("padelya_api.Models.PermissionComponent", null)
                        .WithMany()
                        .HasForeignKey("PermissionComponentId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.RolComposite", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("padelya_api.Models.Court", b =>
                {
                    b.HasOne("padelya_api.Models.Complex", "Complex")
                        .WithMany("Courts")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("padelya_api.Models.CourtAvailability", b =>
                {
                    b.HasOne("padelya_api.Models.Court", "Court")
                        .WithMany("Availability")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("padelya_api.Models.User", b =>
                {
                    b.HasOne("padelya_api.Models.Person", "Person")
                        .WithOne()
                        .HasForeignKey("padelya_api.Models.User", "PersonId");

                    b.HasOne("padelya_api.Models.RolComposite", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.UserStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("padelya_api.Models.SimplePermission", b =>
                {
                    b.HasOne("padelya_api.Models.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("padelya_api.Models.Complex", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("padelya_api.Models.Court", b =>
                {
                    b.Navigation("Availability");
                });

            modelBuilder.Entity("padelya_api.Models.Module", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
