// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using padelya_api.Data;

#nullable disable

namespace padelya_api.Migrations
{
    [DbContext(typeof(PadelYaDbContext))]
    [Migration("20250616032813_RenameFields")]
    partial class RenameFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolCompositePermission", b =>
                {
                    b.Property<int>("PermissionComponentId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionComponentId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolCompositePermission");

                    b.HasData(
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 2,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 3,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 4,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 5,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 6,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 7,
                            RoleId = 100
                        },
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 6,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 7,
                            RoleId = 101
                        },
                        new
                        {
                            PermissionComponentId = 1,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 2,
                            RoleId = 102
                        },
                        new
                        {
                            PermissionComponentId = 7,
                            RoleId = 102
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Booking"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CourtManagement"
                        },
                        new
                        {
                            Id = 3,
                            Name = "UserManagement"
                        },
                        new
                        {
                            Id = 4,
                            Name = "RoleManagement"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tournaments"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Classes"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.PermissionComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("PermissionComponents");

                    b.HasDiscriminator<string>("PermissionType").HasValue("PermissionComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("padelya_api.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("PersonType").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("padelya_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("padelya_api.Models.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.RolComposite", b =>
                {
                    b.HasBaseType("padelya_api.Models.PermissionComponent");

                    b.HasDiscriminator().HasValue("Composite");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Admin",
                            PermissionType = "Composite"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Teacher",
                            PermissionType = "Composite"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Player",
                            PermissionType = "Composite"
                        });
                });

            modelBuilder.Entity("padelya_api.Models.SimplePermission", b =>
                {
                    b.HasBaseType("padelya_api.Models.PermissionComponent");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.HasIndex("FormId");

                    b.HasDiscriminator().HasValue("Simple");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Booking_View",
                            PermissionType = "Simple",
                            FormId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Booking_Create",
                            PermissionType = "Simple",
                            FormId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "CourtManagement_View",
                            PermissionType = "Simple",
                            FormId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "UserManagement_View",
                            PermissionType = "Simple",
                            FormId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "RoleManagement_View",
                            PermissionType = "Simple",
                            FormId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tournaments_View",
                            PermissionType = "Simple",
                            FormId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Classes_View",
                            PermissionType = "Simple",
                            FormId = 6
                        });
                });

            modelBuilder.Entity("padelya_api.Models.Player", b =>
                {
                    b.HasBaseType("padelya_api.Models.Person");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("padelya_api.Models.Teacher", b =>
                {
                    b.HasBaseType("padelya_api.Models.Person");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("RolCompositePermission", b =>
                {
                    b.HasOne("padelya_api.Models.PermissionComponent", null)
                        .WithMany()
                        .HasForeignKey("PermissionComponentId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.RolComposite", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("padelya_api.Models.Person", b =>
                {
                    b.HasOne("padelya_api.Models.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("padelya_api.Models.Person", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("padelya_api.Models.User", b =>
                {
                    b.HasOne("padelya_api.Models.RolComposite", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelya_api.Models.UserStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("padelya_api.Models.SimplePermission", b =>
                {
                    b.HasOne("padelya_api.Models.Form", "Form")
                        .WithMany("Permissions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("padelya_api.Models.Form", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("padelya_api.Models.User", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
